{% set name = "dliswriter" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dliswriter-{{ version }}.tar.gz
  sha256: 20806f105c1d4bbb56977c08c353fbf7a3d0d0801f4ab65b4b707ae63588312b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - h5py
    - numpy >=1.19.2
    - progressbar2
    - typing-extensions >=4.0.1

test:
  imports:
    - dliswriter
  commands:
    - pip check
  requires:
    - python 3.9
    - pip

about:
  home: https://github.com/well-id/dliswriter
  summary: An open-source Python package for writing DLIS files.
  description: |
    dliswriter allows you to specify the structure, data, and metadata of your DLIS file 
    in a simple and flexible fashion, and takes care of creating the binary file. 
    The file writing time is pretty much linearly dependent on the amount of data (number of rows).
  license: MIT
  license_file: LICENSE
  doc_url: https://well-id-widcdliswriter.readthedocs-hosted.com/index.html
  dev_url: https://github.com/well-id/dliswriter

extra:
  recipe-maintainers:
    - the-mysh
    - nup002
