{% set name = "dliswriter" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dliswriter-{{ version }}.tar.gz
  sha256: 1ba0f4486bd5f08894c0f74b8164e8070bae34c496b30a6f5638aa5f46eb7c53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy >=1.19.2
    - progressbar2
    - typing-extensions >=4.0.1

test:
  imports:
    - dliswriter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/well-id/dliswriter
  summary: An open-source Python package for writing DLIS files.
  description: |
    dliswriter allows you to specify the structure, data, and metadata of your DLIS file 
    in a simple and flexible fashion, and takes care of creating the binary file. 
    The file writing time is pretty much linearly dependent on the amount of data (number of rows).
  license: MIT
  license_file: LICENSE
  doc_url: https://well-id-widcdliswriter.readthedocs-hosted.com/index.html
  dev_url: https://github.com/well-id/dliswriter

extra:
  recipe-maintainers:
    - the-mysh
    - nup002
